%%{init: {'themeVariables': { 'lineColor': '#5c6d8e', 'fontSize': '18px', 'fontWeight': 'bold'}}}%%
flowchart TD
  ta_root["Nivel táctico"]
  classDef rootTa fill:#7a1e2e,stroke:#7a1e2e,color:#fff
  class ta_root rootTa
